---
title: "Final Group Project"
output: pdf_document
Authors: Hannah Peha, Laura Uribe, Blake Jones
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

## DATA115 Final Project


```{r pressure, echo=FALSE}

Happiness_Report <- read_excel("Happiness Report.xlsx")
head(Happiness_Report)

ExtremePlaces <- read_excel("ExtremePlaces.xlsx")
head(ExtremePlaces)

Norm_HappinessReport <- read_excel("Norm_HappinessReport.xlsx")
head(Norm_HappinessReport)

```


```{r cor}
library("GGally")

ggpairs(Happiness_Report, columns=c(3:11),title="World Happiness Correlation Report")

ggpairs(ExtremePlaces, columns=c(3,4,5,6,7,8,10,11),title="Extreme Places Correlation Report")

ggpairs(Norm_HappinessReport, columns=c(3:11),title="Normal Places Correlation Report")

```

```{r compare correlation findings}

plot(Norm_HappinessReport$`Life Ladder` ~ Norm_HappinessReport$`Log GDP per capita`)
plot(Norm_HappinessReport$`Life Ladder` ~ Norm_HappinessReport$`Social support`)
plot(Norm_HappinessReport$`Life Ladder` ~ Norm_HappinessReport$`Healthy life expectancy at birth`)

plot(Norm_HappinessReport$`Social support` ~ Norm_HappinessReport$`Log GDP per capita`)
plot(Norm_HappinessReport$`Log GDP per capita`~ Norm_HappinessReport$`Social support`)
plot(Norm_HappinessReport$`Healthy life expectancy at birth`~ Norm_HappinessReport$`Log GDP per capita`)
plot(Norm_HappinessReport$`Social support`~ Norm_HappinessReport$`Healthy life expectancy at birth`)

```



```{r X_Laura Analysis}

boxplot(`Life Ladder`~`Year`,
data=Happiness_Report,
ylim = range(2:8),
main="Global happiness over time",
xlab="Year",
ylab="Life Ladder",
col="thistle1",
border="black"
)

boxplot(`Life Ladder`~`Year`,
data=Norm_HappinessReport,
ylim = range(2:8),
main="'Normal' happiness over time",
xlab="Year",
ylab="Life Ladder",
col="pink",
border="black"
)

boxplot(`Life Ladder`~`Year`,
data=ExtremePlaces,
ylim = range(2:8),
main="'Extreme' happiness over time",
xlab="Year",
ylab="Life Ladder",
col="pink",
border="black"
)

Happiness_Report[Happiness_Report$`Life Ladder`<3 & Happiness_Report$Year>2017, ]
ExtremePlaces[ExtremePlaces$`Life Ladder`<4.5, ]

ggplot(Happiness_Report,aes(x=`Life Ladder`,y=`Region`, color=`Region`)) + geom_point(size=3)+ 
xlab("Life Ladder")+ylab("Region")+
ggtitle("Happiness Distribution for Regions")

A2 <- ggplot(Norm_HappinessReport,aes(x=`Log GDP per capita`,y=`Life Ladder`, color=`Region`)) + geom_point(size=2) + ggtitle("'Normal' Regions")
A2 + expand_limits(x=c(6.5,12), y=c(2, 8.1))
A1 <- ggplot(ExtremePlaces,aes(x=`Log GDP per capita`,y=`Life Ladder`, color=`Country`))+ geom_point(size=3)+ ggtitle("'Extreme' Regions")
A1 + expand_limits(x=c(6.5,12), y=c(2, 8.1))


B2 <- ggplot(Norm_HappinessReport,aes(x=`Social support`,y=`Life Ladder`,color=Region)) + geom_point(size=2) + ggtitle("'Normal' Regions")
B2 + expand_limits(x=c(0.4,1), y=c(2, 8.1))
B1 <- ggplot(ExtremePlaces,aes(x=`Social support`,y=`Life Ladder`,color=`Country`)) + geom_point(size=3)+ ggtitle("'Extreme' Regions")
B1 + expand_limits(x=c(0.4,1), y=c(2, 8.1))
  
C2 <- ggplot(Norm_HappinessReport,aes(x=`Healthy life expectancy at birth`,y=`Life Ladder`,color=Region)) + geom_point(size=2) + ggtitle("'Normal' Regions")
C2 + expand_limits(x=c(45,77), y=c(2, 8.1))
C1 <- ggplot(ExtremePlaces,aes(x=`Healthy life expectancy at birth`,y=`Life Ladder`,color=`Country`)) + geom_point(size=3)+ ggtitle("'Extreme' Regions")
C1 +expand_limits(x=c(45,77), y=c(2, 8.1))

```
```{r X_Hannah Analysis}

library(rdist)

#Create 2020 Data frame
Norm_HappinessReport2020 <- Norm_HappinessReport[Norm_HappinessReport$Year == "2020",]
head(Norm_HappinessReport2020)

#Create Object for PCA
Happiness <- Norm_HappinessReport2020[,4:11]

#PCA with scaled and centered data
Happiness_PCA <- prcomp(Happiness,center=TRUE,scale=TRUE)

summary(Happiness_PCA)

#Add first and second principal components to data frame
Norm_HappinessReport2020$pc1 <- Happiness_PCA$x[,1]
Norm_HappinessReport2020$pc2 <- Happiness_PCA$x[,2]

#Plot first and second principal components colored according to the Life Ladder
ggplot(Norm_HappinessReport2020,aes(x=pc1, y=pc2, color=`Life Ladder`)) +
  geom_point() +
  ggtitle("Happiness PCA") +
  theme(plot.title = element_text(face="bold", hjust=0.5)) +
  xlab("PC1 (44.2% explained var.)") +
  ylab("PC2 (19.4% explained var.)") +
  scale_color_gradientn(colors=rainbow(5))

round(Happiness_PCA$rotation,2)

```
```{r Hannah_ggbiplot}

#biplot code

hannah_ggbiplot <- function(pcobj, choices = 1:2, scale = 1, pc.biplot = TRUE, 
                      obs.scale = 1 - scale, var.scale = scale, 
                      groups = NULL, ellipse = FALSE, ellipse.prob = 0.68, 
                      labels = NULL, labels.size = 3, alpha = 1, 
                      var.axes = TRUE, 
                      circle = FALSE, circle.prob = 0.69, 
                      varname.size = 3, varname.adjust = 1.5, 
                      varname.abbrev = FALSE, ...)
{
  library(ggplot2)
  library(plyr)
  library(scales)
  library(grid)

  stopifnot(length(choices) == 2)

  # Recover the SVD
 if(inherits(pcobj, 'prcomp')){
    nobs.factor <- sqrt(nrow(pcobj$x) - 1)
    d <- pcobj$sdev
    u <- sweep(pcobj$x, 2, 1 / (d * nobs.factor), FUN = '*')
    v <- pcobj$rotation
  } else if(inherits(pcobj, 'princomp')) {
    nobs.factor <- sqrt(pcobj$n.obs)
    d <- pcobj$sdev
    u <- sweep(pcobj$scores, 2, 1 / (d * nobs.factor), FUN = '*')
    v <- pcobj$loadings
  } else if(inherits(pcobj, 'PCA')) {
    nobs.factor <- sqrt(nrow(pcobj$call$X))
    d <- unlist(sqrt(pcobj$eig)[1])
    u <- sweep(pcobj$ind$coord, 2, 1 / (d * nobs.factor), FUN = '*')
    v <- sweep(pcobj$var$coord,2,sqrt(pcobj$eig[1:ncol(pcobj$var$coord),1]),FUN="/")
  } else if(inherits(pcobj, "lda")) {
      nobs.factor <- sqrt(pcobj$N)
      d <- pcobj$svd
      u <- predict(pcobj)$x/nobs.factor
      v <- pcobj$scaling
      d.total <- sum(d^2)
  } else {
    stop('Expected a object of class prcomp, princomp, PCA, or lda')
  }

  # Scores
  choices <- pmin(choices, ncol(u))
  df.u <- as.data.frame(sweep(u[,choices], 2, d[choices]^obs.scale, FUN='*'))

  # Directions
  v <- sweep(v, 2, d^var.scale, FUN='*')
  df.v <- as.data.frame(v[, choices])

  names(df.u) <- c('xvar', 'yvar')
  names(df.v) <- names(df.u)

  if(pc.biplot) {
    df.u <- df.u * nobs.factor
  }

  # Scale the radius of the correlation circle so that it corresponds to 
  # a data ellipse for the standardized PC scores
  r <- sqrt(qchisq(circle.prob, df = 2)) * prod(colMeans(df.u^2))^(1/4)

  # Scale directions
  v.scale <- rowSums(v^2)
  df.v <- r * df.v / sqrt(max(v.scale))

  # Change the labels for the axes
  if(obs.scale == 0) {
    u.axis.labs <- paste('standardized PC', choices, sep='')
  } else {
    u.axis.labs <- paste('PC', choices, sep='')
  }

  # Append the proportion of explained variance to the axis labels
  u.axis.labs <- paste(u.axis.labs, 
                       sprintf('(%0.1f%% explained var.)', 
                               100 * pcobj$sdev[choices]^2/sum(pcobj$sdev^2)))

  # Score Labels
  if(!is.null(labels)) {
    df.u$labels <- labels
  }

  # Grouping variable
  if(!is.null(groups)) {
    df.u$groups <- groups
  }

  # Variable Names
  if(varname.abbrev) {
    df.v$varname <- abbreviate(rownames(v))
  } else {
    df.v$varname <- rownames(v)
  }

  # Variables for text label placement
  df.v$angle <- with(df.v, (180/pi) * atan(yvar / xvar))
  df.v$hjust = with(df.v, (1 - varname.adjust * sign(xvar)) / 2)

  # Base plot
  g <- ggplot(data = df.u, aes(x = xvar, y = yvar)) + 
          xlab(u.axis.labs[1]) + ylab(u.axis.labs[2]) + coord_equal()

  if(var.axes) {
    # Draw circle
    if(circle) 
    {
      theta <- c(seq(-pi, pi, length = 50), seq(pi, -pi, length = 50))
      circle <- data.frame(xvar = r * cos(theta), yvar = r * sin(theta))
      g <- g + geom_path(data = circle, color = muted('white'), 
                         size = 1/2, alpha = 1/3)
    }

    # Draw directions
    g <- g +
      geom_segment(data = df.v,
                   aes(x = 0, y = 0, xend = xvar, yend = yvar),
                   arrow = arrow(length = unit(1/2, 'picas')), 
                   color = muted('purple'))
  }

  # Draw either labels or points
  if(!is.null(df.u$labels)) {
    if(!is.null(df.u$groups)) {
      g <- g + geom_text(aes(label = labels, color = groups), 
                         size = labels.size)
    } else {
      g <- g + geom_text(aes(label = labels), size = labels.size)      
    }
  } else {
    if(!is.null(df.u$groups)) {
      g <- g + geom_point(aes(color = groups), alpha = alpha)
    } else {
      g <- g + geom_point(alpha = alpha)      
    }
  }

  # Overlay a concentration ellipse if there are groups
  if(!is.null(df.u$groups) && ellipse) {
    theta <- c(seq(-pi, pi, length = 50), seq(pi, -pi, length = 50))
    circle <- cbind(cos(theta), sin(theta))

    ell <- ddply(df.u, 'groups', function(x) {
      if(nrow(x) <= 2) {
        return(NULL)
      }
      sigma <- var(cbind(x$xvar, x$yvar))
      mu <- c(mean(x$xvar), mean(x$yvar))
      ed <- sqrt(qchisq(ellipse.prob, df = 2))
      data.frame(sweep(circle %*% chol(sigma) * ed, 2, mu, FUN = '+'), 
                 groups = x$groups[1])
    })
    names(ell)[1:2] <- c('xvar', 'yvar')
    g <- g + geom_path(data = ell, aes(color = groups, group = groups))
  }

  # Label the variable axes
  if(var.axes) {
    g <- g + 
    geom_text(data = df.v, 
              aes(label = varname, x = xvar, y = yvar, 
                  angle = angle, hjust = hjust), 
              color = 'purple', size = varname.size)
  }
  # Change the name of the legend for groups
  # if(!is.null(groups)) {
  #   g <- g + scale_color_brewer(name = deparse(substitute(groups)), 
  #                               palette = 'Dark2')
  # }

  # TODO: Add a second set of axes

  return(g)
}


hannah_ggbiplot(Happiness_PCA, obs.scale = 0.5) +
  scale_y_continuous(limits = c(-2.5, 2.5)) +
  scale_x_continuous(limits = c(-4, 4)) +
  ggtitle("Happiness Biplot") +
  theme(plot.title = element_text(face="bold", hjust=0.5))

```
